### ISSUE TITLE
Mixing up commentary details

### ISSUE THREAD

**Issue by ghost** [ntyndall/footballstats#22]
Need to move the names
```
  allNames <- c(
    commentaryNames %>% paste0('.h'),
    commentaryNames %>% paste0('.sdh'),
    commentaryNames %>% paste0('.a'),
    commentaryNames %>% paste0('.sda'),
    c('strength.h', 'strength.sdh', 'strength.a', 'strength.sda')
  )
```
so that strength home goes in the middle.

Needs updated for both building and saving the data scales, and in both calculating model and generating predictions!

**Comment by ntyndall** [comment]
Method has totally changed and this feature is irrelevant
